# Generated by Django 4.2.6 on 2023-12-07 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='date_written',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(default='Im idiot!', verbose_name='Question Text'),
        ),
    ]
