# Generated by Django 4.2.6 on 2023-11-03 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='correct_answers_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='durachyo', max_length=50, verbose_name='User Nickname'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_written',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='questions', to='main.tags'),
        ),
    ]
