# Generated by Django 4.2.6 on 2023-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_question_questions_alter_tags_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='amount_of_likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
